---
- name: Check if we can do a inventory
  setup:
    gather_subset: min
  failed_when: false
  register: minimal

#- debug: var=minimal

- block:

  - name: Verify python installation
    raw: python3 -V
    failed_when: false
    changed_when: false
    register: python_installed
  
  - name: Try to install python
    include_tasks: pre_python.yml
    when: python_installed.rc != 0
  
  - meta: clear_facts

  - name: Init facts
    setup:

  when: ( ansible_distribution_file_variety is not defined ) or ( minimal.rc is defined and minimal.rc != 0 )

- set_fact:
     incname: "pre_{{ ansible_distribution_file_variety | lower | map('trim') | join }}.yml"

#- debug: var=incname

- name: Trying to find distribution prerequisites 
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ incname }}"
    - "default.yml"
